# .streamlit/config.toml
[connections.mydb] #定义「mydb」为连接的模块名
dialect = "mysql" # 类型
username = "root" # 账号
password = "huanqlu0123" # 密码
host = "39.98.120.220" # 地址
database = "spider" # 数据库
type = "sql" # 有些会用到，这里指定不变即可